version: "3.8"
services:
    nodeserver:
        build:
            context: ./server/app
    nginx:
        restart: always
        build:
            context: ./server/nginx
        ports:
            - "8080:80"